# Generated by Django 3.2.5 on 2021-07-08 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='account.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='students', to='school.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='school.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ManyToManyField(related_name='teachers', to='school.School'),
        ),
    ]
